import { exportCatalog, firebaseReady, importCatalog, login, logout, removeProduct, saveProduct, saveSiteSettings, seedInitialProducts, subscribeAppearance, subscribeProducts, watchAdmin } from "./firebase-service.js";

const $ = (selector) => document.querySelector(selector);
const loginView = $("#loginView"); const adminView = $("#adminView"); const productModal = $("#productModal"); const appearanceModal = $("#appearanceModal");
let products = []; let appearance = {}; let unsubscribeProducts; let unsubscribeAppearance;

function showLogin(message = "") { loginView.classList.remove("hidden"); adminView.classList.add("hidden"); $("#loginMessage").textContent = message; }
async function showAdmin() { loginView.classList.add("hidden"); adminView.classList.remove("hidden"); await seedInitialProducts(); }
function money(value) { return `S/ ${Number(value || 0).toFixed(2)}`; } function stockOf(item) { return Number(item.stock ?? (item.available === false ? 0 : 10)); }
function renderRows() {
  $("#adminStatus").textContent = `${products.length} productos · ${products.reduce((total, item) => total + stockOf(item), 0)} unidades`;
  $("#productRows").innerHTML = products.map((item) => `<tr><td><div class="table-product"><img src="${item.image}" alt=""><span><strong>${item.name}</strong><small>${item.code} · ${item.size || ""}${item.featured ? " · Destacado":""}</small></span></div></td><td>${item.category}</td><td><strong>${item.salePrice ? `${money(item.salePrice)} <s>${money(item.price)}</s>`:money(item.price)}</strong></td><td><span class="status ${stockOf(item)>0?"ok":"off"}">${stockOf(item)} unidades</span></td><td>${item.visible ? "Sí":"No"}</td><td><div class="row-actions"><button data-edit="${item.id}">Editar</button><button class="danger" data-delete="${item.id}">Eliminar</button></div></td></tr>`).join("");
}
function openProduct(item = {}) {
  $("#modalTitle").textContent = item.id ? "Editar producto":"Nuevo producto"; $("#productId").value = item.id || ""; $("#oldImage").value = item.image || "";
  ["code","name","price","salePrice","stock","size","badge","description","sortOrder"].forEach((key) => { $(`#${key}`).value = key === "stock" && item.id ? stockOf(item) : item[key] ?? (key === "sortOrder" ? products.length + 1 : key === "stock" ? 1 : ""); });
  $("#category").value = item.category || "Alcancías"; $("#featured").checked = Boolean(item.featured); $("#available").checked = item.available !== false; $("#visible").checked = item.visible !== false; $("#imageFile").value = ""; $("#saveMessage").textContent = ""; productModal.classList.remove("hidden");
}
function closeProduct() { productModal.classList.add("hidden"); }
function openAppearance() {
  const defaults = { businessName:"Manitos Creativas Edrizel", heroEyebrow:"Hecho a mano en Moquegua", heroTitle:"Pequeñas manos.", heroAccent:"Grandes recuerdos.", heroDescription:"Figuras y alcancías artesanales para compartir momentos inolvidables en familia.", heroNote1:"✦ Yeso cerámico", heroNote2:"✦ Diseños únicos", heroNote3:"✦ Hecho con cariño", heroCardTitle:"Tu primera alcancía", heroCardText:"Lista para pintar y decorar", servicesEyebrow:"Eventos y experiencias creativas", servicesTitle:"Llevamos la creatividad a tu celebración", servicesDescription:"Creamos momentos especiales para que niños y familias pinten, compartan y se lleven un recuerdo hecho por ellos mismos.", eventTitle:"Cumpleaños y bautizos", eventText:"Organizamos actividades de pintado de alcancías o pintura en caballetes, adaptadas a la temática y edad de los invitados.", schoolTitle:"Jardines y colegios", schoolText:"Realizamos jornadas creativas para grupos escolares, ideales para compartir, aprender y desarrollar la imaginación.", customTitle:"Alcancías personalizadas y envíos", customText:"Preparamos alcancías personalizadas según el modelo o temática elegida y coordinamos su entrega o envío.", servicesNote:"Cuéntanos la fecha, cantidad de niños y temática que deseas.", storyEyebrow:"Nuestra esencia", storyTitle:"Más que una figura, un momento para recordar", storyText:"Elaboramos cada pieza con dedicación para que padres e hijos pinten juntos y conviertan una figura en un recuerdo propio.", footerTagline:"Arte, juego y momentos en familia.", contactTitle:"Pedidos y consultas", sitePhone:"+51 937 344 997", siteLocation:"Moquegua, Perú" };
  ["businessName","heroEyebrow","heroTitle","heroAccent","heroDescription","heroNote1","heroNote2","heroNote3","heroCardTitle","heroCardText","servicesEyebrow","servicesTitle","servicesDescription","eventTitle","eventText","schoolTitle","schoolText","customTitle","customText","servicesNote","storyEyebrow","storyTitle","storyText","footerTagline","contactTitle","sitePhone","siteLocation","instagram","facebook","tiktok"].forEach((key) => { $(`#${key}`).value = appearance[key] || defaults[key] || ""; });
  $("#logoFile").value = ""; $("#heroFile").value = ""; $("#appearanceMessage").textContent = ""; appearanceModal.classList.remove("hidden");
}
function closeAppearance() { appearanceModal.classList.add("hidden"); }

$("#loginForm").addEventListener("submit", async (event) => { event.preventDefault(); $("#loginMessage").textContent = "Ingresando…"; try { await login($("#email").value, $("#password").value); } catch (error) { $("#loginMessage").textContent = error.message; } });
$("#logoutButton").addEventListener("click", logout); $("#newButton").addEventListener("click", () => openProduct()); $("#closeModal").addEventListener("click", closeProduct); $("#cancelButton").addEventListener("click", closeProduct); $("#appearanceButton").addEventListener("click", openAppearance); $("#closeAppearance").addEventListener("click", closeAppearance); $("#cancelAppearance").addEventListener("click", closeAppearance);
$("#productRows").addEventListener("click", async (event) => { if (event.target.dataset.edit) openProduct(products.find((item) => item.id === event.target.dataset.edit)); if (event.target.dataset.delete) { const item = products.find((product) => product.id === event.target.dataset.delete); if (confirm(`¿Eliminar definitivamente ${item.name}?`)) await removeProduct(item); } });
$("#productForm").addEventListener("submit", async (event) => { event.preventDefault(); const product = {}; ["productId","code","name","category","price","salePrice","stock","size","badge","description","sortOrder"].forEach((key) => { product[key === "productId" ? "id":key] = $(`#${key}`).value.trim(); }); product.image = $("#oldImage").value; product.featured = $("#featured").checked; product.available = $("#available").checked; product.visible = $("#visible").checked; const file = $("#imageFile").files[0]; if (!product.image && !file) { $("#saveMessage").textContent = "Selecciona una fotografía."; return; } $("#saveButton").disabled = true; $("#saveMessage").textContent = "Optimizando y guardando…"; try { await saveProduct(product, file); closeProduct(); } catch (error) { $("#saveMessage").textContent = error.message; } finally { $("#saveButton").disabled = false; } });
$("#appearanceForm").addEventListener("submit", async (event) => { event.preventDefault(); const settings = { ...appearance }; ["businessName","heroEyebrow","heroTitle","heroAccent","heroDescription","heroNote1","heroNote2","heroNote3","heroCardTitle","heroCardText","servicesEyebrow","servicesTitle","servicesDescription","eventTitle","eventText","schoolTitle","schoolText","customTitle","customText","servicesNote","storyEyebrow","storyTitle","storyText","footerTagline","contactTitle","sitePhone","siteLocation","instagram","facebook","tiktok"].forEach((key) => { settings[key] = $(`#${key}`).value.trim(); }); $("#saveAppearanceButton").disabled = true; $("#appearanceMessage").textContent = "Guardando cambios…"; try { await saveSiteSettings(settings, $("#logoFile").files[0], $("#heroFile").files[0]); closeAppearance(); } catch (error) { $("#appearanceMessage").textContent = error.message; } finally { $("#saveAppearanceButton").disabled = false; } });
$("#backupButton").addEventListener("click", async () => { const data = await exportCatalog(); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type:"application/json" })); link.download = `respaldo-manitos-${new Date().toISOString().slice(0,10)}.json`; link.click(); URL.revokeObjectURL(link.href); });
$("#restoreFile").addEventListener("change", async (event) => { if (!event.target.files[0] || !confirm("¿Restaurar este respaldo? Los productos existentes con el mismo código se actualizarán.")) return; try { await importCatalog(JSON.parse(await event.target.files[0].text())); alert("Respaldo restaurado correctamente."); } catch (error) { alert(error.message); } event.target.value = ""; });

if (!firebaseReady) showLogin("Firebase está pendiente de configuración."); else watchAdmin(async (user) => {
  if (!user) { unsubscribeProducts?.(); unsubscribeAppearance?.(); unsubscribeProducts = null; unsubscribeAppearance = null; showLogin(); return; }
  await showAdmin();
  unsubscribeProducts ||= subscribeProducts((items) => { products = items; renderRows(); }, (error) => { $("#adminStatus").textContent = error.message; }, true);
  unsubscribeAppearance ||= subscribeAppearance((data) => { appearance = data; if (appearance.logo) document.querySelectorAll("[data-site-logo]").forEach((image) => { image.src = appearance.logo; }); });
});
