import { firebaseReady, login, logout, removeProduct, saveProduct, seedInitialProducts, subscribeProducts, watchAdmin } from "./firebase-service.js";

const loginView = document.querySelector("#loginView"); const adminView = document.querySelector("#adminView"); const modal = document.querySelector("#productModal"); let products = []; let unsubscribeProducts = null;
function showLogin(message = "") { loginView.classList.remove("hidden"); adminView.classList.add("hidden"); document.querySelector("#loginMessage").textContent = message; }
async function showAdmin() { loginView.classList.add("hidden"); adminView.classList.remove("hidden"); await seedInitialProducts(); }
function renderRows() { document.querySelector("#adminStatus").textContent = `${products.length} productos en el catálogo`; document.querySelector("#productRows").innerHTML = products.map((item) => `<tr><td><div class="table-product"><img src="${item.image}" alt=""><span><strong>${item.name}</strong><small>${item.code} · ${item.size || ""}</small></span></div></td><td>${item.category}</td><td><strong>S/ ${Number(item.price).toFixed(2)}</strong></td><td><span class="status ${item.available ? "ok":"off"}">${item.available ? "Disponible":"Agotado"}</span></td><td>${item.visible ? "Sí":"No"}</td><td><div class="row-actions"><button data-edit="${item.id}">Editar</button><button class="danger" data-delete="${item.id}">Eliminar</button></div></td></tr>`).join(""); }
function openModal(item = {}) { document.querySelector("#modalTitle").textContent = item.id ? "Editar producto":"Nuevo producto"; document.querySelector("#productId").value = item.id || ""; document.querySelector("#oldImage").value = item.image || ""; ["code","name","price","size","description","sortOrder"].forEach((key) => document.querySelector(`#${key}`).value = item[key] ?? (key === "sortOrder" ? products.length + 1 : "")); document.querySelector("#category").value = item.category || "Alcancías"; document.querySelector("#available").checked = item.available !== false; document.querySelector("#visible").checked = item.visible !== false; document.querySelector("#imageFile").value = ""; document.querySelector("#saveMessage").textContent = ""; modal.classList.remove("hidden"); }
function closeModal() { modal.classList.add("hidden"); }

document.querySelector("#loginForm").addEventListener("submit", async (event) => { event.preventDefault(); const message = document.querySelector("#loginMessage"); message.textContent = "Ingresando…"; try { await login(document.querySelector("#email").value, document.querySelector("#password").value); showAdmin(); } catch (error) { message.textContent = error.message; } });
document.querySelector("#logoutButton").addEventListener("click", () => logout()); document.querySelector("#newButton").addEventListener("click", () => openModal()); document.querySelector("#closeModal").addEventListener("click", closeModal); document.querySelector("#cancelButton").addEventListener("click", closeModal);
document.querySelector("#productRows").addEventListener("click", async (event) => { const editId = event.target.dataset.edit; const deleteId = event.target.dataset.delete; if (editId) openModal(products.find((item) => item.id === editId)); if (deleteId) { const item = products.find((product) => product.id === deleteId); if (confirm(`¿Eliminar definitivamente ${item.name}?`)) await removeProduct(item); } });
document.querySelector("#productForm").addEventListener("submit", async (event) => { event.preventDefault(); const saveButton = document.querySelector("#saveButton"); const message = document.querySelector("#saveMessage"); const product = { id:document.querySelector("#productId").value, code:document.querySelector("#code").value.trim(), name:document.querySelector("#name").value.trim(), category:document.querySelector("#category").value, price:document.querySelector("#price").value, size:document.querySelector("#size").value.trim(), description:document.querySelector("#description").value.trim(), image:document.querySelector("#oldImage").value, available:document.querySelector("#available").checked, visible:document.querySelector("#visible").checked, sortOrder:document.querySelector("#sortOrder").value }; const file = document.querySelector("#imageFile").files[0]; if (!product.image && !file) { message.textContent = "Selecciona una fotografía."; return; } saveButton.disabled = true; message.textContent = "Optimizando y guardando…"; try { await saveProduct(product, file); closeModal(); } catch (error) { message.textContent = error.message; } finally { saveButton.disabled = false; } });

if (!firebaseReady) showLogin("Firebase está pendiente de configuración."); else watchAdmin(async (user) => {
  if (!user) { if (unsubscribeProducts) unsubscribeProducts(); unsubscribeProducts = null; showLogin(); return; }
  await showAdmin();
  if (!unsubscribeProducts) unsubscribeProducts = subscribeProducts((items) => { products = items; renderRows(); }, (error) => { document.querySelector("#adminStatus").textContent = error.message; }, true);
});
